# Generated by Django 4.1 on 2023-02-04 08:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GoalStatus",
            new_name="GoalExpense",
        ),
        migrations.CreateModel(
            name="GoalBump",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=13
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goals.goals"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
    ]
