# Generated by Django 4.0.4 on 2022-06-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggyhistory',
            name='piggy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='piggy.piggies'),
            preserve_default=False,
        ),
    ]
